language: python
python:
  - "2.7"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  
script: 
  - py.test ./whois.py test --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
