language: python
python:
  - "2.7"

install:
  - "pip install -r requirements-dev.txt"
  
script: 
  - py.test whois.py --doctest-modules -v --cov whois --cov-report term-missing

after_success:
  - coveralls
